AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-lambda-only

  Sample SAM Template for sam-lambda-only
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3

# Application dependencies in a manifest file: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html
# Issues with numpy https://github.com/numpy/numpy/issues/27338
# https://github.com/aws/aws-sam-cli/issues/7429
Resources:
  APICallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pipeline_1/
      Handler: api_call_and_store.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 600 
      Environment:
        Variables:
          S3_SOURCE: econolens-staging-area
      Role: arn:aws:iam::975373241930:role/EconolensAPICALLANDSTOREAccess

  DataEnrichmentFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: pipeline_2/
      Handler: data_enrichment.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 600 # 10 minutes
      Environment:
        Variables:
          S3_SOURCE: econolens-staging-area
          S3_DESTINATION: econolens-data-enriched
      Role: arn:aws:iam::975373241930:role/EconolensDATAENRICHMENTAccess


      # Events:
      #   HelloWorld:
      #     Type: Api 
      #     Properties:
      #       Path: /hello
      #       Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunction:
    Description: "API call Lambda Function ARN"
    Value: !GetAtt APICallFunction.Arn

