AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-econolens-agent
  AI components of the Econolens project consisting of agent, action groups, lambdas, agent alias

Parameters:
  AgentName:
    Type: String
    Default: EconolensAgent
    Description: Name for the Bedrock Agent
  FoundationModelId:
    Type: String
    Default: amazon.nova-lite-v1:0 #anthropic.claude-3-5-sonnet-20240620-v1:0
    Description: Foundation model ID for the agent (Agent optimised Foundation models only)

Globals:
  Function:
    Timeout: 300 # seconds
    MemorySize: 256 # MB
    Tracing: Active
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        BEDROCK_KNOWLEDGE_BASE_ID: A1233
        POWERTOOLS_METRICS_NAMESPACE: bedrock-agent-demo
        POWERTOOLS_SERVICE_NAME: bedrock-agent-demo

Resources:
   # --- BEDROCK AGENT ---
  BedrockAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Ref AgentName # this is working
      AgentResourceRoleArn: !GetAtt BedrockAgentExecutionRole.Arn
      Description: "Agent for economic reporting and question answering. Required: Time-period dates (inclusive). Optional: Topic, entity keyword"
      FoundationModel: !Ref FoundationModelId
      Instruction: |
        You are an economic analyst that generates economic reports or answers specific questions about economic events and their effect on the economy.  You have access to a bedrock knowledge base that has up-to-date data until the present day, so you do not need to be trained with the data. These time periods can be as small as one day (the start and end date are the same), or as long as one year. 

        Every request requires the user to specify a time-period over which economic events took place but the user does not have to explicitly state so, the start and end date are inclusive. For example, if the user says "Give me the economic report for the month of December in the year 2000" , the time-period is the whole month of December in the year 2020, enter 2020-12-01 as start_date_str and 2025-12-31 and end_date_str.

        You have access to the following tools:
        getTopicCorporate: this is used for retrieving data on corporate topics
        getTopicLaborMarket: this is used for retrieving data on corporate topics

        These are the instructions for the tasks you can perform:
        1. REPORT GENERATION: When asked to generate a report or provide a comprehensive overview:
          - Extract the time-period and extract start_date_str and end_date_str parameters from the prompt. Prompt the user if a time-period is not specified
          - Get data for each of following economic topics: corporate, labor market
          - Summarise the retrieve data and generate a well-structured report with one paragraph per topic capturing the main points without irrelevant details
          - Place a title on each paragraph consisting of the topic

        2. QUESTION ANSWERING: When asked a specific question:
          - Extract the time-period and extract start_date_str and end_date_str parameters from the prompt. Prompt the user if a time-period is not specified
          - Call get_topic_corporate if the question is related to an entity (ie: trump, powell, white house)
          - Call get_topic_corporate if the question is related to an economic topic (ie: inflation, labor_market, economy_long_term)
          - Provide a direct, concise answer based on the retrieved data containing the main points

        Always think step-by-step:
        - First, determine if this is a report generation request or a specific question 
        - At each stage, state the function you are going to call and the parameters you will pass
        - Then, call the appropriate function(s)
        - Finally, format your response appropriately
      ########################################################################################################################
      ActionGroups:
        - ActionGroupName: GetTopicCorporate
          Description: "Use this tool to get information on corporate topics"
          ActionGroupExecutor:
            Lambda: !GetAtt RetrieveTopicCorporate.Arn
          ActionGroupState: ENABLED
          FunctionSchema:
            Functions:
              - Name: GetInformation
                Description: |
                  Get information on corporate topics
                Parameters:
                  end_date_str:
                    Description: "The end date of the time-period"
                    Required: True
                    Type: string
                  start_date_str:
                    Description: "The end date of the time-period"
                    Required: True
                    Type: string
        - ActionGroupName: GetTopicLaborMarket
          Description: "Use this tool to get information on labor market topics"
          ActionGroupExecutor:
            Lambda: !GetAtt RetrieveTopicLaborMarket.Arn
          ActionGroupState: ENABLED
          FunctionSchema:
            Functions:
              - Name: GetInformation
                Description: |
                  Get information on corporate topics
                Parameters:
                  end_date_str:
                    Description: "The end date of the time-period"
                    Required: True
                    Type: string
                  start_date_str:
                    Description: "The end date of the time-period"
                    Required: True
                    Type: string

  # --- LAMBDA FUNCTIONS AND RB POLICIES---
  # To prevent circular reference when we need agent reference, use "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/${AgentName}"
  # Instead of the ARN -> !GetAtt BedrockAgent.AgentArn that is generated after deployment
  # The above is false
  # RB policies state who can invoke the lambda
  RetrieveTopicCorporate:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AgentFunctionsRole.Arn
      CodeUri: lambda/retrieve_topic/corporate/
      Handler: app.lambda_handler
      PackageType: Zip
      # Layers:
      #   - !Ref ModelLayer

  AgentFunctionsForRetrieveTopicCorporateRoleBedrock:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RetrieveTopicCorporate
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      #SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt BedrockAgent.AgentArn
  
  RetrieveTopicLaborMarket:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AgentFunctionsRole.Arn
      CodeUri: lambda/retrieve_topic/labor_market/
      Handler: app.lambda_handler
      PackageType: Zip
      # Layers:
      #   - !Ref ModelLayer

  AgentFunctionsForRetrieveTopLMRoleBedrock:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RetrieveTopicLaborMarket
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      #SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt BedrockAgent.AgentArn

  # --- IAM ROLES ---
  # Principal, who is allowed to assume the role
  # Resource, specific resource(s) the role (role actions) applies to
  AgentFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role for Agent Lambda functions to assume
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
            #Resource: !GetAtt BedrockAgent.AgentArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess

  BedrockAgentExecutionRole:
    # Agent does not need to access Bedrock KB directly, only action groups
    Type: AWS::IAM::Role
    Properties:
      Description: A role for Agent to assume
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - bedrock.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        # Theoretically: This Res Pol allows bedrock to invoke the lambdas listed
        # Attach individual lambdas Arns
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                - !GetAtt RetrieveTopicCorporate.Arn
                - !GetAtt RetrieveTopicLaborMarket.Arn
        - PolicyName: BedrockModelAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "bedrock:ApplyGuardrail"
                  - "bedrock:List*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "bedrock:GetAgentVersion"
                  - "bedrock:GetAgentAlias"
                  - "bedrock:GetAgentMemory"
                  - "bedrock:GetAgent"
                  - "bedrock:GetAgentActionGroup"
                  - "bedrock:GetAgentKnowledgeBase"
                  - "bedrock:ListAgentVersions"
                  - "bedrock:ListAgentActionGroups"
                  - "bedrock:ListAgentKnowledgeBases"
                  - "bedrock:ListAgentAliases"
                Resource: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/${AgentName}"
              - Effect: Allow
                Action:
                  - "bedrock:InvokeModel"
                  - "bedrock:InvokeModelWithResponseStream"
                  - "bedrock:GetInferenceProfile"
                  - "bedrock:GetFoundationModel"
                Resource: "*" # can place specific model arn here
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              # - Effect: Allow
              #   Action:
              #     - "bedrock:GetGuardrail"
              #     - "bedrock:ApplyGuardrail"
              #     - "bedrock:ListGuardrails"
              #   Resource: !GetAtt BedrockAgent.AgentArn
              
        

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
