AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'python3.11 Built with SAM Template build-with-image for sam-econolens

  '
Globals:
  Function:
    Timeout: 600
    Environment:
      Variables:
        S3_SOURCE: econolens-staging-area
        S3_DESTINATION: econolens-data-enriched
Resources:
  APICallFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Role: arn:aws:iam::975373241930:role/EconolensAPICALLANDSTOREAccess
      ImageUri: apicallfunction:python3.11-v1
    Metadata:
      DockerContext: C:\Work\Folder_1\Project_folder\LLM_project_1_EconoLens\EconoLens\sam-econolens\functions\pipeline_1_api_call
      DockerTag: python3.11-v1
      Dockerfile: Dockerfile
      SamResourceId: APICallFunction
  DataEnrichmentlFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Role: arn:aws:iam::975373241930:role/EconolensAPICALLANDSTOREAccess
      ImageUri: dataenrichmentlfunction:python3.11-v1
    Metadata:
      DockerContext: C:\Work\Folder_1\Project_folder\LLM_project_1_EconoLens\EconoLens\sam-econolens\functions\pipeline_2_data_enrichment
      DockerTag: python3.11-v1
      Dockerfile: Dockerfile
      SamResourceId: DataEnrichmentlFunction
