# Remember to build with sam build --use-container --parallel, 
# Container images are created locally https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/using-sam-cli-build.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11
  Built with SAM Template build-with-image deployment package for sam-econolens

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    #Timeout: 300 # seconds
    Environment:
      Variables:
        S3_STAGE: econolens-staging-area
        S3_ENRICH: econolens-data-enriched
        S3_CHUNK: econolens-data-chunked
        # Change this when KB restarts
        BEDROCK_KB_ID: J689XHGM6B 
        BEDROCK_KB_DATASOURCE_ID: ABC123

Resources:
  # IAM roles created with AWS managed IAM policies
  EconolensAPICallRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
  
  EconolensDataEnrichmentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  # Pipeline 3 invokes the embedding model on bedrock, access S3
  EconolensDataChunkRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess

  EconolensKBIngestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      # https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-prereq-permissions-general.html
      Policies:
        - PolicyName: BedrockKBManagementPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:GetKnowledgeBase
                  - bedrock:ListKnowledgeBases
                  - bedrock:UpdateKnowledgeBase
                  - bedrock:DeleteKnowledgeBase
                  - bedrock:StartIngestionJob
                  - bedrock:GetIngestionJob
                  - bedrock:ListIngestionJobs
                  - bedrock:StopIngestionJob
                  - bedrock:TagResource
                  - bedrock:UntagResource
                Resource: '*' 

  # Infrastructure
  # Default timeout is 300 seconds. Longer functions is the full 900 seconds (15 mins)
  NewsPipelineStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/news_pipeline.asl.json
      DefinitionSubstitutions:
        APICallFunctionArn: !GetAtt APICallFunction.Arn
        DataEnrichmentFunctionArn: !GetAtt DataEnrichmentFunction.Arn
        DataChunkFunctionArn: !GetAtt DataChunkFunction.Arn
        BedrockKBIngestFunctionArn: !GetAtt BedrockKBIngestFunction.Arn
      # Run at 10 am everyday. Use context data from EventBridge scheduler not StepFunctions
      # https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html#contextobject-format
      # https://docs.aws.amazon.com/scheduler/latest/UserGuide/managing-schedule-context-attributes.html
      Events:
        DailyTrigger:
          Type: ScheduleV2
          Properties:
            Name: DailyTrigger
            Description: "Run the data pipeline every day at 10 AM Pacific Time"
            ScheduleExpression: "cron(0 10 * * ? *)"
            ScheduleExpressionTimezone: "America/Los_Angeles"
            Input: '{"batch_date": "<aws.scheduler.scheduled-time>"}'
      # SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      # Gives the State machine permission to invoke
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref APICallFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DataEnrichmentFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DataChunkFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BedrockKBIngestFunction

  # This is not the best syntax for defining lambda container images. Specify the handler function
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html
  APICallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt EconolensAPICallRole.Arn
      Timeout: 300
      MemorySize: 256
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/pipeline_1_api_call
      DockerTag: python3.11-v1
    
  DataEnrichmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt EconolensDataEnrichmentRole.Arn
      Timeout: 300
      # increasedfor loading spacy library, en_core_web_md model. default is 128 MB https://docs.aws.amazon.com/lambda/latest/dg/configuration-memory.html#configuration-memory-use-cases 
      MemorySize: 2048
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/pipeline_2_data_enrichment
      DockerTag: python3.11-v1

  DataChunkFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt EconolensDataChunkRole.Arn
      # increased for text embedding model, langchain library
      Timeout: 900
      MemorySize: 3008 #4096
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/pipeline_3_data_chunking
      DockerTag: python3.11-v1

  BedrockKBIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: !GetAtt EconolensKBIngestRole.Arn
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/pipeline_4_bedrockKB_ingest
      DockerTag: python3.11-v1
  
# Outputs:
#   APICallFunctionArn:
#     Description: ARN of the API Call Lambda function
#     Value: !GetAtt APICallFunction.Arn


